INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Grande Sertão: Veredas', 'Nova Fronteira', '2005-01-06', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Grande Sertão: Veredas', 'Nova Fronteira', '2015-11-26', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Grande Sertão: Veredas', 'Companhia das Letras', '2019-07-08', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Dom Casmurro', 'Penguin Companhia das Letras', '2016-10-26', 'Machado de Assis');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Dom Casmurro', 'Antofágica', '2020-12-06', 'Machado de Assis');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Sagarana', 'Nova Fronteira', '2015-04-12', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Sagarana', 'Global', '2019-11-06', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Quincas Borba', 'Penguin Companhia das Letras', '2012-05-20', 'Machado de Assis');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Quincas Borba', 'Antofágica', '2021-03-06', 'Machado de Assis');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Vidas Secas', 'Record', '2014-02-26', 'Graciliano Ramos');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Vidas Secas', 'Record', '2018-03-26', 'Graciliano Ramos');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Cem Anos de Solidão', 'Record', '2014-05-08', 'Gabriel García Márquez');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Cem Anos de Solidão', 'Record', '2019-08-16', 'Gabriel García Márquez');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Crime e Castigo', 'Todavia', '2019-06-22', 'Fiódor Dostoiévski');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Crime e Castigo', 'Editora 34', '2019-11-26', 'Fiódor Dostoiévski');