INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Grande Sertão: Veredas', 'Nova Fronteira', '2019-11-26', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Grande Sertão: Veredas', 'Nova Fronteira', '2019-11-26', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Grande Sertão: Veredas', 'Companhia das Letras', '2019-11-26', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Dom Casmurro', 'Penguin Companhia das Letras', '2019-11-26', 'Machado de Assis');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Dom Casmurro', 'Antofágica', '2019-11-26', 'Machado de Assis');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Sagarana', 'Nova Fronteira', '2019-11-26', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Sagarana', 'Global', '2019-11-26', 'João Guimarães Rosa');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Quincas Borba', 'Penguin Companhia das Letras', '2019-11-26', 'Machado de Assis');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Quincas Borba', 'Antofágica', '2019-11-26', 'Machado de Assis');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Vidas Secas', 'Record', '2019-11-26', 'Graciliano Ramos');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Vidas Secas', 'Record', '2019-11-26', 'Graciliano Ramos');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Cem Anos de Solidão', 'Record', '2019-11-26', 'Gabriel García Márquez');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Cem Anos de Solidão', 'Record', '2019-11-26', 'Gabriel García Márquez');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Crime e Castigo', 'Todavia', '2019-11-26', 'Fiódor Dostoiévski');
INSERT INTO tb_book(name,publisher,publication_date,author) VALUES('Crime e Castigo', 'Editora 34', '2019-11-26', 'Fiódor Dostoiévski');